# Generated by Django 4.0.5 on 2022-06-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(default=False, max_length=100)),
                ('D_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=70)),
                ('Last_Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.IntegerField(default=0)),
                ('Bonus', models.IntegerField(default=0)),
                ('Phone', models.IntegerField(default=0)),
                ('Hire_date', models.DateField()),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Details.role')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Details.department')),
            ],
        ),
    ]
