# Generated by Django 4.0.5 on 2022-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='First_Name',
            field=models.CharField(max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Last_Name',
            field=models.CharField(max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=70),
        ),
    ]
