# Generated by Django 4.0.5 on 2022-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Details', '0002_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Bonus',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='First_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Last_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.IntegerField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(default=' '),
        ),
    ]
