# Generated by Django 4.0.5 on 2022-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Details', '0003_alter_employee_bonus_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='D_Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='R_Name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
