# Generated by Django 4.0.5 on 2022-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Details', '0004_alter_department_d_name_alter_role_r_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.IntegerField(default=''),
        ),
    ]
